export const projectData = [
	{
		title: 'Movie App',
		langauges: 'React, Firebase',
		liveUrl: 'https://ironstone-movie-app.netlify.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/react-movie-app',
		img: null,
		alt: 'Movie App',
		isNew: true,
	},
	{
		title: 'Blog App',
		languages: 'React, Firebase',
		liveUrl: 'https://ironstone-react-recipe-app.netlify.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/blog-fire-react-app',
		img: null,
		alt: 'Blog App',
		isNew: false,
	},
	{
		title: 'Recipe App',
		languages: 'React',
		liveUrl: 'ironstone-react-recipe-app.netlify.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/react-recipe-app',
		img: null,
		alt: 'Recipe App',
		isNew: false,
	},
	{
		title: 'User Generator',
		languages: 'JavaScript, HTML, CSS',
		liveUrl: 'https://random-user-generator-ten.vercel.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/RANDOM-USER-GENERATOR',
		img: null,
		alt: 'User Generator',
		isNew: false,
	},
	{
		title: 'Guess The Number',
		languages: 'JavaScript',
		liveUrl: 'https://ironstone-a.github.io/FIND-THE-NUMBER-GAME/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/FIND-THE-NUMBER-GAME',
		img: null,
		alt: 'Guess The Number',
		isNew: false,
	},
	{
		title: 'Checkout',
		languages: 'JavaScript',
		liveUrl: 'https://ironstone-a.github.io/CHECKOUT-PROJECT/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/CHECKOUT-PROJECT',
		img: null,
		alt: 'Checkout',
		isNew: false,
	},
	{
		title: 'Contact App',
		languages: 'React',
		liveUrl: 'https://ironstone-fire-contact-app.netlify.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/fire-contact-app',
		img: null,
		alt: 'Contact App',
		isNew: false,
	},
	{
		title: "Language Card",
		languages: 'React',
		liveUrl: 'https://ironstone-react-language-cards.vercel.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/react-language-cards',
		img: null,
		alt: "Language Card",
		isNew: false,
	},
	
	{
		title: "Tour Place",
		languages: 'React',
		liveUrl: 'https://ironstone-react-tour-place.vercel.app/',
		gitHubUrl: 'https://github.com/IRONSTONE-A/TOUR-PLACE',
		img: null,
		alt: "Tour Place",
		isNew: false,
	},
	
];
